badge:
  image: registry.gitlab.vgiscience.org/tud_ifk/miniconda-cidefault
  before_script:
      # initialize conda shell
      - conda init bash
      - source ~/.bashrc
      # activate default ci_env from registry image
      # contains anybadge
      - conda activate ci_env
  stage: badge
  script:
      # create badges with version from latest tag
    - version_var=$(git tag | grep -E 'v[0-9].[0-9].[0-9]' | tail -n 1 | cut -c2-)
    - echo "Version for badges $version_var"
    - anybadge -l version --value="${version_var}" --file=version.svg --color=green
    - anybadge -l doi --value="10.25532/OPARA-90" --file=doi.svg --color=blue
    - anybadge -l pipeline --value=passing --file=pipeline.svg passing=green failing=red
  artifacts:
    paths:
      # quote because * is a
      # special character in YAML
      - '*.svg'
  only:
  - master

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp *.svg .public
    - mv .public public
  artifacts:
    name: pages
    paths:
    - public
  only:
  - master

