# Pair notebooks in subfolders of 'notebooks' to py and md files in subfolders 'py' and 'md'
# files in subfolder "py" will be renamed (leading underscore),
# as a means to not raise name conflicts when imported in python 
default_jupytext_formats = "notebooks///ipynb,md///md,py///_/.py"